spring.application.name=RealMateAI

#spring.profiles.active = local

# 1. C?u hình k?t n?i Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 2. C?u hình g?i Mail (n?u có dùng)
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# 3. C?u hình b?o m?t JWT (n?u có dùng)
jwt.secret=${JWT_SECRET}